name: CI
on:
  push:
    branches: [ main, release/** ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build & Test
        run: ./gradlew clean :lib:build :lib:test --no-daemon
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Python dependencies
        run: pip install -r tools/requirements.txt
      
      - name: Run LUT optimization demo
        run: ./gradlew :lib:lutOptimize
      
      - name: Generate plot
        run: python3 tools/plot_lut_opt.py docs/lut_opt/results.csv docs/lut_opt/plot.png
      
      - name: Upload plot artifact
        uses: actions/upload-artifact@v4
        with:
          name: lut-optimization-plot
          path: docs/lut_opt/plot.png
